import coat from '../assets/media/icons/coat.svg'
import dress from '../assets/media/icons/dress.svg'
import glasses from '../assets/media/icons/glasses.svg'
import hat from '../assets/media/icons/hat.svg'
import jacket from '../assets/media/icons/jacket.svg'
import jacket from '../assets/media/icons/jacket.svg'